# Generated by Django 5.0.4 on 2024-04-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('queuniqueid', models.CharField(max_length=50)),
                ('visiable', models.BooleanField(default=True)),
                ('questionownerid', models.CharField(max_length=50)),
                ('queaddeddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
