# Generated by Django 5.0.4 on 2024-04-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsOfQue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=50)),
                ('ansstr', models.TextField()),
                ('ansownerid', models.CharField(max_length=50)),
                ('visiable', models.BooleanField(default=True)),
                ('ansdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
