# Generated by Django 5.0.4 on 2024-04-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_ansofque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addquestions',
            name='queuniqueid',
        ),
    ]
